import React from "react";
import { AlertTriangle, PhoneCall, ShieldAlert } from "lucide-react";

interface MedicalDisclaimerProps {
  elevatedRiskAlert?: boolean;
}

export function MedicalDisclaimer({ elevatedRiskAlert = false }: MedicalDisclaimerProps) {
  return (
    <div className="space-y-3">
      {elevatedRiskAlert && (
        <div className="p-5 rounded-3xl border border-amber-500/35 bg-amber-500/15 backdrop-blur-2xl text-amber-950 dark:text-amber-100 shadow-xs">
          <div className="flex items-start gap-3.5">
            <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-bold text-amber-950 dark:text-amber-100 mb-1">
                Clinical Consultation Recommended
              </p>
              <p className="text-amber-900 dark:text-amber-200/90 leading-relaxed text-xs sm:text-sm">
                Consider discussing your result and cardiovascular risk factors with a qualified
                healthcare professional or cardiologist for diagnostic testing and clinical evaluation.
              </p>
            </div>
          </div>
        </div>
      )}

      <div className="glass-card p-5 rounded-3xl text-slate-700 dark:text-slate-300 text-xs leading-relaxed">
        <div className="flex items-start gap-3.5">
          <ShieldAlert className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="font-bold text-slate-900 dark:text-white uppercase tracking-wider text-[11px]">
              Medical Disclaimer
            </p>
            <p className="text-slate-600 dark:text-slate-300">
              This application provides an educational risk estimate generated by a machine-learning
              model. It is not a medical diagnosis and should not replace professional medical
              advice, examination, or clinical testing. If you have symptoms or concerns about your
              heart health, consult a qualified healthcare professional immediately.
            </p>
            <p className="text-slate-500 dark:text-slate-400 pt-1 flex items-center gap-1.5 font-medium">
              <PhoneCall className="w-3.5 h-3.5 text-rose-500 inline" />
              If you are experiencing acute chest pain, pressure, shortness of breath, or emergency
              symptoms, call 911 (or your local emergency services) immediately.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
